apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: dpa-instance
  namespace: openshift-adp
spec:
  backupLocations:
    - name: default
      velero:
        config:
          region: minio
          profile: "default"
          s3ForcePathStyle: 'true'
          s3Url: 'http://registry.hypershiftbm-2.lab:9002'
        credential:
          key: cloud
          name: cloud-credentials
        default: true
        objectStorage:
          bucket: example-oadp
          prefix: backup-objects
        provider: aws
  snapshotLocations:
    - velero:
        provider: aws
        config:
          region: region-one
          profile: "default"
        credential:
          key: cloud
          name: cloud-credentials
  configuration:
    nodeAgent:
      enable: true
      uploaderType: kopia
    velero:
      defaultPlugins:
        - openshift
        - aws
        - kubevirt
        - csi
      customPlugins:
        - name: hypershift-oadp-plugin
          image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-oadp-plugin-main:latest
      resourceTimeout: 2h